### ISSUE TITLE
CNF errors

### ISSUE THREAD

**Issue by WolframKahl** [seereason/atp-haskell#2]
`simpcnf` currently is:
````
simpcnf :: (JustPropositional pf, JustLiteral lit, Ord lit) =>
           (AtomOf pf -> AtomOf lit) -> pf -> Set (Set lit)
simpcnf ca fm =
    foldPropositional (\_ _ _ -> go) (\_ -> go) tf (\_ -> go) fm
    where
      tf False = Set.empty
      tf True = singleton Set.empty
      go = let cjs = Set.filter (not . trivial) (purecnf ca fm) in
           Set.filter (\c -> not (setAny (\c' -> Set.isProperSubsetOf c' c) cjs)) cjs
````
Here, the results for `True` and `False` are swapped (see p. 61). As result, we get:
````
> Data.Logic.ATP.Prop.cnf' false
True
> Data.Logic.ATP.Prop.cnf' true
False
````
and even:
````
> Data.Logic.ATP.DP.dplisat false
True
> Data.Logic.ATP.DP.dplisat true
False
> Data.Logic.ATP.DP.dplbsat false
True
> Data.Logic.ATP.DP.dplbsat true
False
````

**Comment by ddssff** [comment]
Oh my, thanks!  I thought all the outputs matched those in the book.

**Comment by ddssff** [comment]
Unfortunate that doesn't change the result of test35.

**Comment by ddssff** [comment]
Unfortunately I've been away from this code for a long time, are you suggesting this change?  Could you write a test case for it based on test35?

```diff --git a/src/Data/Logic/ATP/Prop.hs b/src/Data/Logic/ATP/Prop.hs
index 46249b5..029552a 100644
--- a/src/Data/Logic/ATP/Prop.hs
+++ b/src/Data/Logic/ATP/Prop.hs
@@ -1087,8 +1087,8 @@ simpcnf :: (JustPropositional pf, JustLiteral lit, Ord lit) =>
 simpcnf ca fm =
     foldPropositional (\_ _ _ -> go) (\_ -> go) tf (\_ -> go) fm
     where
-      tf False = Set.empty
-      tf True = singleton Set.empty
+      tf True = Set.empty
+      tf False = singleton Set.empty
       go = let cjs = Set.filter (not . trivial) (purecnf ca fm) in
            Set.filter (\c -> not (setAny (\c' -> Set.isProperSubsetOf c' c) cjs)) cjs
```

**Comment by WolframKahl** [comment]
> Unfortunate that doesn't change the result of test35.

It only affects the naked propositional constants `T` and `F`.

[Prop-cnf-2024-03-13.patch.txt](https://github.com/seereason/atp-haskell/files/14589224/Prop-cnf-2024-03-13.patch.txt)

**Comment by WolframKahl** [comment]
(It also affects ground propositions like `⊥∨⊤`, since they simplify to single constants.)

**Comment by ddssff** [comment]
How did you happen to notice this package?  You are the first as far as I know.

**Comment by WolframKahl** [comment]
I noticed the package by looking for automated theorem proving on hackage.

I noticed the issue by trying out whether I could drive some decision procedures, and I actually tried  `⊥∨⊤`...

**Comment by ddssff** [comment]
Issue resolved, closing.
